# Generated by Django 2.2.3 on 2019-10-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nb_like',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
